---
- name: uninstall wireshark on web, nfs and db servers
  hosts: webservers, nfs, db
  become: yes
  tasks:
  - name: ensure wireshark is uninstalled
    yum:
      name: wireshark
      state: removed

- name: Remove testfolder
  hosts: all
  become: yes
  tasks:
    - name: Recursively Remove directory
      file:
        path: /home/testfolder
        state: absent

- name: uninstall wireshark
  hosts: lb
  become: yes
  tasks:
    - name: ensure wireshark is is uninstalled
      apt:
        name: wireshark
        state: absent
        autoremove: yes
        purge: yes
        autoclean: yes