---
- name: update web, nfs and db servers
  hosts: webservers
  become: yes
  tasks:
  - name: ensure wireshark is installed at latest version
    yum:
      name: wireshark
      state: latest

- name: Set time zone & create directory on all servers
  hosts: all
  become: yes
  tasks:
    - name: create testfolder directory if it does not exists
      file:
        path: /home/testfolder
        state: directory
        mode: '0755'

    - name: Set timezone
      timezone:
        name: Asia/Singapore
        hwclock: local

- name: update LB server
  hosts: lb
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
