# ---
# - name: Include dynamic variables 
#   hosts: all
#   tasks:
#     - import_playbook: ../static-assignments/common.yml 
#     - include_playbook: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

# - name: Webserver assignment
#   hosts: webservers
#   tasks:
#    - import_playbook: ../static-assignments/webservers.yml


---
- hosts: all
- name:  dynamic variables 
  import_playbook: ../Static-assignments/common.yml 
  include: ../Dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: webservers
- name: Webserver assignment
  import_playbook: ../Static-assignments/webservers.yml

- hosts: uatdb
- name: Database Assignment
  import_playbook:  ../Static-assignments/database.yml
