---
- hosts: all
- name:  dynamic variables 
  import_playbook: ../Static-assignments/common.yml 
  include: ../Dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: webservers
- name: Webserver assignment
  import_playbook: ../Static-assignments/webservers.yml

- hosts: uatdb
- name: Database Assignment
  import_playbook:  ../Static-assignments/database.yml

- hosts: uatlb
- name: loadbalancer Assignment
  import_playbook:  ../Static-assignments/loadbalancer.yml
  when: load_balancer_is_required
