---
- name: Include dynamic variables 
  hosts: all
  tasks:
    - import_playbook: ../static-assignments/common.yml 
    - include_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Webserver assignment
  hosts: webservers
  tasks:
   - import_playbook: ../static-assignments/webservers.yml

- name: Database Assignment
  hosts: uatdb
  tasks:
    - import_playbook:  ../static-assignments/database.yml
